 apiVersion: v1
 kind: Service
 metadata:
   name: nginx
   labels:
     name: nginx
   namespace: staging
 spec:
   type: NodePort
   ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: http
   - name: https
     port: 443
     protocol: TCP
     targetPort: https
     nodePort: 30100
   selector:
     name: nginx
