apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx: |
    #!/bin/bash

    # settings
    export ENABLE_SSL="true"
    export SERVER_NAME="corekube.com"

    # directory paths
    ## letsencrypt
    export LETSENCRYPT_DIR="/srv/etc/letsencrypt"
    export SSL_CERTS_DIR="$LETSENCRYPT_DIR/live/corekube.com"
    export SSL_DHPARAMS="$LETSENCRYPT_DIR/dhparams.pem"
    export LETSENCRYPT_ACME_DIR="$LETSENCRYPT_DIR/webrootauth/.well-known/acme-challenge"
    ## nginx
    export ROOT_DIR="/srv/data/prod/dest"
